# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: 3.3.0
sudo: true
cache: packages
warnings_are_errors: false

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_bioc EBImage
  - ./travis-tool.sh install_bioc_deps

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
